<a href="https://colab.research.google.com/github/qwasd34/DEV_DATA/blob/main/Scikit_Learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## OrdinalEncoder vs. OneHotEncoder

In [1]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

data = [['seoul'], ['tokyo'], ['beijing']]
encoder = OrdinalEncoder()
result = encoder.fit_transform(data)

In [2]:
encoder.categories_

[array(['beijing', 'seoul', 'tokyo'], dtype=object)]

순서있는 데이터들, 수치가 의미가있을때 사용

In [9]:
result

array([[1.],
       [2.],
       [0.]])

순서가 없는, 데이터간의관계가 독립일때

In [13]:
enc = OneHotEncoder(sparse=False)
enc.fit(data)
X_ohe = enc.transform(data)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [14]:
enc.categories_

[array(['beijing', 'seoul', 'tokyo'], dtype=object)]

In [15]:
X_ohe

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

fit  + transform 한큐에

In [16]:
enc = OneHotEncoder(sparse=False)
X_ohe = enc.fit_transform(data)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [17]:
X_ohe

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

레이블 전처리할때

In [20]:
from sklearn.preprocessing import LabelEncoder

y = ['recurrence-events', 'no-recurrence-events', 'recurrence-events']

In [21]:
label_encoder = LabelEncoder()
y_labeled = label_encoder.fit_transform(y)

print(y_labeled)

[1 0 1]


## Scaler

숫자 필드값의 범위 표준화

In [22]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
import numpy as np

X_train = np.array([[ 1., -1.,  2.],
    [ 2.,  0.,  0.],
    [ 0.,  1., -1.]])

평균이 0 표준편차가 1

각 값에서 평균을 빼고 이를 표준편차로 나눔, 값의 분포를 정규분포를 따르게 변환

In [24]:
scaler = StandardScaler().fit(X_train)
X_scaled = scaler.transform(X_train)
print(X_scaled)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


각값에서 최솟값을 빼고 (최대-최소)로 나눔
최대 최소를 안주면 0-1 사이로 변환

In [25]:
scaler = MinMaxScaler().fit(X_train)
X_scaled = scaler.transform(X_train)
print(X_scaled)

[[0.5        0.         1.        ]
 [1.         0.5        0.33333333]
 [0.         1.         0.        ]]


## Imputer

결측치채우기

In [26]:
import numpy as np
from sklearn.impute import SimpleImputer

# Example dataset with missing values
data = np.array([
    [1, np.nan, 3],
    [4, 3, np.nan],
    [np.nan, 6, 9],
    [8, 5, 2]
])

평귭값으로 결측치채원

In [27]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputed_data = imputer.fit_transform(data)

In [28]:
print("Original Data:")
print(data)
print("\nImputed Data:")
print(imputed_data)

Original Data:
[[ 1. nan  3.]
 [ 4.  3. nan]
 [nan  6.  9.]
 [ 8.  5.  2.]]

Imputed Data:
[[1.         4.66666667 3.        ]
 [4.         3.         4.66666667]
 [4.33333333 6.         9.        ]
 [8.         5.         2.        ]]


다른 컬럼의 값을 비교해 대체, .명확하게 알기 힘들어

In [29]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

iterative_imputer = IterativeImputer(max_iter=10, random_state=0)
imputed_data = iterative_imputer.fit_transform(data)

In [30]:
# Display the original and imputed datasets
print("Original Data:")
print(data)
print("\nImputed Data:")
print(imputed_data)

Original Data:
[[ 1. nan  3.]
 [ 4.  3. nan]
 [nan  6.  9.]
 [ 8.  5.  2.]]

Imputed Data:
[[ 1.         -0.78464705  3.        ]
 [ 4.          3.          4.66634615]
 [ 4.32700692  6.          9.        ]
 [ 8.          5.          2.        ]]


## Pipeline 사용해보기

In [31]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

X, y = make_classification(random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

75 개 레코드, 20개의 컬럼

In [32]:
X_train.shape

(75, 20)

In [36]:
X_test.shape

(25, 20)

In [37]:
scaler = StandardScaler().fit(X_train)
X_scaled = scaler.transform(X_train)

In [38]:
lr = LogisticRegression()
lr.fit(X_scaled, y_train)

LogisticRegression()

In [39]:
X_test_scaled = scaler.transform(X_test)
predicted = lr.predict(X_test_scaled)

In [40]:
from sklearn.metrics import classification_report

classificationReport = classification_report(y_test, predicted)
print(classificationReport)

              precision    recall  f1-score   support

           0       1.00      0.93      0.97        15
           1       0.91      1.00      0.95        10

    accuracy                           0.96        25
   macro avg       0.95      0.97      0.96        25
weighted avg       0.96      0.96      0.96        25



### let's utilize Pipeline which simplifies everything

In [41]:
pipe = make_pipeline(StandardScaler(), LogisticRegression())
pipe.fit(X_train, y_train)
pipe.score(X_test, y_test)

0.96

Accuracy 가 기본으로